### ISSUE TITLE
FEATURE: Toogle to hide forks

### ISSUE THREAD

**Issue by Akurosia** [kalilistic/neat-plugins-plus#1]
When i check the list e.g. for checking out new plugins i see 100x forks of eg delvui.
Would it be possible to hide forks as a toggle?

**Comment by kalilistic** [comment]
I'll take a look - it's a pretty dumb UI at the moment. I thought I'd avoid this by only using forks with some unique commits but delvui seems to have a lot of active variations/developers for sure.

**Comment by kalilistic** [comment]
Slow but not forgotten. I'll be releasing an update in a week or so - switching over to something a little more flexible.

**Comment by kalilistic** [comment]
Added! So much for a week or so though... :)
