### ISSUE TITLE
Plugins missing / updated date wrong [stopping updates for day to fix now!]

### ISSUE THREAD

**Issue by tssailzz8** [kalilistic/neat-plugins-plus#11]
https://github.com/pynom/ChatBubbles
![image](https://user-images.githubusercontent.com/52206101/164875035-08ac9781-9bbb-4305-9552-726dc1c0ff09.png)
![image](https://user-images.githubusercontent.com/52206101/164875097-3a12c279-aa26-4dc0-85dd-63a00b2c5e30.png)

**Comment by kalilistic** [comment]
Thanks will look into it.

**Comment by tssailzz8** [comment]
it do not updata recently?

**Comment by kalilistic** [comment]
Was getting stuck on forks again. I just made an update and should start updating again slowly now.

I'm working on a bigger update to avoid these issues.

**Comment by tssailzz8** [comment]
it not true 
![image](https://user-images.githubusercontent.com/52206101/172614373-2f2986bf-acc5-4e90-bd6a-04b0df6c6546.png)
![image](https://user-images.githubusercontent.com/52206101/172614394-f98ac2e4-714e-4f96-b0a7-f7dd421181dc.png)

**Comment by kalilistic** [comment]
I'm going to suspend updates shortly for a day or so while I migrate to my new github crawler. This should fix missing plugins and the date issue. The date issue is because I was using the repository's updated date which can change from other stuff like repository meta data. The new version will use the last commit date.

**Comment by kalilistic** [comment]
Update is live. Let me know if any issues.

**Comment by tssailzz8** [comment]
i can not find SimpleTweaksPlugin in web https://github.com/Caraxi/SimpleTweaksPlugin

**Comment by kalilistic** [comment]
Closing this as I think all the issues have been worked out.

**Comment by tssailzz8** [comment]
some plugins not found,like https://github.com/Tischel/InventorySearchBar

**Comment by kalilistic** [comment]
For some reason that plugin doesn't get returned in github's APIs - maybe since it's relatively new. I've added it manually and should show up later today. If you spot any others missing, let me know and I can do the same.
