### ISSUE TITLE
Page not updating

### ISSUE THREAD

**Issue by Genesis-Nova** [kalilistic/neat-plugins-plus#3]
Docs and workflow folders missing from root, hasn't updated in 2 days. just a heads up.

**Comment by kalilistic** [comment]
Hey, thanks for the note. I rebuilt it with VueJS and a few AWS services - so no longer uses docs nor github actions. I'll add a "last updated" date to the page - so it's more visible if everything is working okay.

**Comment by Battler624** [comment]
I was able to see plugins yesterday, nothing showing up today. weird.

**Comment by kalilistic** [comment]
> I was able to see plugins yesterday, nothing showing up today. weird. Edit: Everything is working again.

Will check and logs and keep an eye out... let me know if happens again tho.

**Comment by asevrinsky** [comment]
Appears to be working, but I don't see a single plugin update more recent than Dec 31 -- that can't be right, can it?

**Comment by kalilistic** [comment]
Should show up as updated now. Still tinkering with updating to make sure it's solid.

**Comment by Battler624** [comment]
I don't assume you'll add gitlab support?

**Comment by kalilistic** [comment]
> I don't assume you'll add gitlab support?

Do you mean an issue repo on gitlab? Or something else?

**Comment by Battler624** [comment]
I mean search up repos on GitLab for anything dalamud related (isnt this what you are doing on github? Or is everything done manually)

**Comment by kalilistic** [comment]
> I mean search up repos on GitLab for anything dalamud related (isnt this what you are doing on github? Or is everything done manually)

Ah, makes sense. I think it's worth a new issue with my thoughts there. https://github.com/kalilistic/neat-plugins-plus/issues/4

**Comment by kalilistic** [comment]
I'll keep an eye on it but seems to be updating as expected now. Ran a few times last night.

**Comment by kalilistic** [comment]
Closing as seems to be updated now as expected.
