### ISSUE TITLE
Repos no longer clickable

### ISSUE THREAD

**Issue by oorzkws** [kalilistic/neat-plugins-plus#5]
I'm not sure when this cropped up, but I swear the repo names used to be clickable links

**Comment by kalilistic** [comment]
I mostly rebuilt it two weeks ago so probably then. I can add that back - in the meantime the URL itself is still clickable.

**Comment by oorzkws** [comment]
My mistake - I hadn't realized the list was in a frame with its own scrollbar, so I lost the last column when I resized the window.

**Comment by kalilistic** [comment]
Released a new version with a bunch of clickable links. Thanks!
