### ISSUE TITLE
Updates paused for a few hours (maintenance)

### ISSUE THREAD

**Issue by bladehawkz** [kalilistic/neat-plugins-plus#6]
Last update on the list is the 15th of January, but there have definitely been updates to other repos since, so I assume the list is broken again.

**Comment by kalilistic** [comment]
Hey, I should've posted something. I paused it for a bit to make some bigger data updates. Should have it updating again within a few hours.

**Comment by kalilistic** [comment]
Pushing an update now. You might see no plugins for a little bit while it runs a fresh update. I'll reply here once that's done.

**Comment by kalilistic** [comment]
Updated! I'll leave this open for a bit since I'm actively working on it today and might break something. :)

**Comment by kalilistic** [comment]
I broke something. Looking at it now. :)
