### ISSUE TITLE
API returns incorrect url for xivdev's Penumbra repo

### ISSUE THREAD

**Issue by Zebouski** [kalilistic/neat-plugins-plus#7]
https://github.com/xivdev/Penumbra 's readme says the repo URL to add to dalmud, should be the URL ending in `repo.json`, but this API is returning a url ending in `base_repo.json` 

```
 curl -X 'GET' \
                              'https://api.kalilistic.io/dalamud/repos' \
                            'https://api.kalilistic.io/dalamud/repos''accept: application/json' \
                            | jq | grep "xivdev"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28710  100 28710    0     0  24944      0  0:00:01  0:00:01 --:--:-- 24965
curl: (3) URL using bad/illegal format or missing URL
    "owner": "xivdev",
    "fullName": "xivdev/Penumbra",
    "pluginMasterUrl": "https://raw.githubusercontent.com/xivdev/Penumbra/master/base_repo.json"
```

I noticed this breaking the installation of penumbra via https://github.com/UnknownX7/DalamudRepoBrowser, which is said to use this API

**Comment by kalilistic** [comment]
Will fix this and a few other bugs today. Thanks for letting me know.

**Comment by kalilistic** [comment]
I made a quick fix of changing the penumbra master url to https://raw.githubusercontent.com/xivdev/Penumbra/master/repo.json.
